# 4D_Neural_SDF
setting:
  data_path: "/automount_home_students/zzhang/research/ThirdSemester/project_part2/data/self_record/data/velodyne/"
  pose_path: "/automount_home_students/zzhang/research/ThirdSemester/project_part2/data/self_record/data/kitti_round1_poses.txt"
  calib_path: ""
  output_root: "/automount_home_students/zzhang/research/ThirdSemester/project_part2/code/Shine_PoseTracking/experiments/"
  begin_frame: 0
  end_frame: 4470
  device: "cuda"
  gpu_id: "0"
  hash_buffer_size: 100000000
  
preprocessing:
  min_z: -5.0
  radius: 50.0
  
neuralvoxel:
  leaf_voxel_size: 0.3
  voxel_level_num : 3
  scale_up_factor : 1.5
  feature_dim: 32  
  feature_std: 0.0
  
decoder:
  mlp_level: 3
  mlp_hidden_dim: 256

sampler:
  truncated_sample_range_m: 0.5
  truncated_sample_num: 5
  occupied_sample_range_m: 0.6
  occupied_sample_num: 4
  free_sample_num: 2
  
mapping:
  sliding_window_size: 50
  iterion_num: 80
  batch_size: 16384
  learning_rate: 0.001
  
meshing:
   mesh_resolution: 0.4


