# 4D_Neural_SDF
setting:
  data_path: "F:/UNIVERSITY_BONN/Third Semester/project_part2/data/self_data/data_round1/data/velodyne/"
  pose_path: "F:/UNIVERSITY_BONN/Third Semester/project_part2/data/self_data/data_round1/data/kitti_round1_poses.txt"
  calib_path: ""
  output_root: "./results"
  begin_frame: 0
  end_frame: -1
  device: "cuda"
  gpu_id: "0"
  hash_buffer_size: 100000000


  map_ply: "results/self_000000-004469_full.ply" #path to your reconstructed mesh
  vis_n: 1 #how many frames to estimate and show at a time
  vis_k: 2 #Max frames showing on the map
  

  auto_debug_csv: False
  debug_csv_path: "./results/sdf_debug_full.csv"
  
preprocessing:
  min_z: -5.0
  radius: 30.0
  # min_z: -5.0
  # radius: 40.0
  
neuralvoxel:
  leaf_voxel_size: 0.3
  voxel_level_num : 2
  scale_up_factor : 1.5
  feature_dim: 8
  feature_std: 0.0

decoder:
  mlp_level: 2
  mlp_hidden_dim: 64

sampler:
  truncated_sample_range_m: 0.3
  truncated_sample_num: 6
  occupied_sample_range_m: 0.25
  occupied_sample_num: 3
  free_sample_num: 5

mapping:
  sliding_window_size: 30
  iterion_num: 20
  batch_size: 16384
  learning_rate: 0.001
  
meshing:
   mesh_resolution: 0.2


