# 4D_Neural_SDF
setting:
  data_path: "/home_domuser/s39zzhan/ThirdSemester/project_02/data/cppdata/PLY/"
  pose_path: "/home_domuser/s39zzhan/ThirdSemester/project_02/data/cppdata/Data/gt_poses.txt"
  calib_path: ""
  begin_frame: 0
  end_frame: 6770
  device: "cuda"
  gpu_id: "0"
  hash_buffer_size: 100000000

  output_root: "../results"
  mesh_root: "../results/meshes/"
  
####for vis####
  map_ply: "../results/meshes/zappa_000000-006769_full.ply" #path to your reconstructed mesh
  vis_n: 1 #how many frames to estimate and show at a time
  enable_vis: false
  
preprocessing:
  min_z: -5.0
  radius: 30.0
  
  
neuralvoxel:
  leaf_voxel_size: 0.3
  voxel_level_num : 2
  scale_up_factor : 1.5
  feature_dim: 8  
  feature_std: 0.0
  
decoder:
  mlp_level: 2
  mlp_hidden_dim: 64

sampler:
  truncated_sample_range_m: 0.5
  truncated_sample_num: 6
  occupied_sample_range_m: 0.45
  occupied_sample_num: 4
  free_sample_num: 5
  
mapping: 
  sliding_window_size: 30
  iterion_num: 20
  batch_size: 16384
  learning_rate: 0.001
  
meshing:
   mesh_resolution: 0.2


