# 4D_Neural_SDF
setting:
  data_path: "/export/data/s39zzhan/data/maicity/mai_city/sequence/velodyne/"
  pose_path: "/export/data/s39zzhan/data/maicity/mai_city/sequence/poses.txt"
  calib_path: ""
  output_root: "./results"
  begin_frame: 0
  end_frame: 100
  device: "cuda"
  gpu_id: "0"
  hash_buffer_size: 100000000


  map_ply: "/export/data/s39zzhan/save_data/maicity/maicity.ply" #path to your reconstructed mesh
  vis_n: 1 #how many frames to estimate and show at a time
  vis_k: 2 #Max frames showing on the map
  vis_voxel: 0.01
  
preprocessing:
  min_z: -5.0
  radius: 90.0
  
neuralvoxel:
  leaf_voxel_size: 0.2
  voxel_level_num : 3
  scale_up_factor : 2
  feature_dim: 24  
  feature_std: 0.001
  
decoder:
  mlp_level: 2
  mlp_hidden_dim: 128

sampler:
  truncated_sample_range_m: 0.2
  truncated_sample_num: 5
  occupied_sample_range_m: 0.5
  occupied_sample_num: 2
  free_sample_num: 3
  
mapping:
  sliding_window_size: 30
  iterion_num: 200
  batch_size: 16384
  learning_rate: 0.0005
  
meshing:
   mesh_resolution: 0.4
