# 4D_Neural_SDF
setting:
  data_path: "/automount_home_students/zzhang/research/ThirdSemester/project_part2/data/mai_city/sequence/velodyne/"
  pose_path: "/automount_home_students/zzhang/research/ThirdSemester/project_part2/data/mai_city/sequence/poses.txt"
  calib_path: ""
  output_root: "/automount_home_students/zzhang/research/ThirdSemester/project_part2/code/Shine_PoseTracking/experiments/"
  begin_frame: 4700
  end_frame: 6770
  device: "cuda"
  gpu_id: "0"
  hash_buffer_size: 100000000
  
preprocessing:
  min_z: -5.0
  radius: 30.0
  
neuralvoxel:
  leaf_voxel_size: 0.3
  voxel_level_num : 2
  scale_up_factor : 1.5
  feature_dim: 16  
  feature_std: 0.0
  
decoder:
  mlp_level: 2
  mlp_hidden_dim: 128

sampler:
  truncated_sample_range_m: 0.5
  truncated_sample_num: 3
  occupied_sample_range_m: 0.45
  occupied_sample_num: 2
  free_sample_num: 2
  
mapping:
  sliding_window_size: 30
  iterion_num: 50
  batch_size: 16384
  learning_rate: 0.001
  
meshing:
   mesh_resolution: 0.4