setting:
  incremental: true # false = localization mode
  enable_deskew: false # only works for incremental mode
  data_path: ""
  pose_path: ""
  calib_path: ""
  begin_frame: 0
  end_frame: 10
  device: "cuda"
  gpu_id: "0"
  hash_buffer_size: 100000000

  output_root: "../results"

  map_ply: "" #path to your reconstructed mesh
  vis_n: 1
  enable_vis: false
  
preprocessing:
  min_z: -5.0
  radius: 30.0

  
neuralvoxel:
  leaf_voxel_size: 0.3
  voxel_level_num : 2
  scale_up_factor : 1.5
  feature_dim: 16  
  feature_std: 0.0
  
decoder:
  mlp_level: 2
  mlp_hidden_dim: 128

sampler:
  truncated_sample_range_m: 0.5
  truncated_sample_num: 3
  occupied_sample_range_m: 0.45
  occupied_sample_num: 2
  free_sample_num: 2
  
mapping: 
  sliding_window_size: 30
  iterion_num: 20
  batch_size: 16384
  learning_rate: 0.001
  
meshing:
   mesh_resolution: 0.2
